app: vjepa_wm
nodes: 1
tasks_per_node: 1
cpus_per_task: 8
folder: ${JEPAWM_LOGS}/grandtour_sweep/gt_v2_12f_fps5_r256_dv3vitl16_AdaLN_d12c_4roll_1n_SMOKE
data:
  dataset_type: custom
  datasets:
  - GrandTour
  datasets_weights: null
  seed: 234
  img_size: 256
  validation:
    val_datasets:
    - GrandTour
    num_frames_val: 5
    val_dataset_batch_size: 4
    val_dataset_drop_last: false
    val_dataset_fpcs:
    - 12
    val_dataset_camera_views:
    - hdr_front
    val_viz_rank0_loader: true
  loader:
    batch_size: 2
    num_workers: 6
    pin_mem: true
    persistent_workers: true
  custom:
    split_ratio: null
    frameskip: 1
    action_skip: 1
    state_skip: 1
    normalize_action: false
    traj_subset: true
    filter_first_episodes: null
    filter_tasks: null
    num_hist: null
    num_pred: null
    with_reward: null
    custom_teleop_dset: null
  droid:
    camera_frame: null
    camera_views:
    - hdr_front
    droid_to_rcasa_action_format: 1
    rcasa_to_droid_action_format: null
    fps: 5
    dataset_fpcs:
    - 12
    mpk_manifest_patterns:
    - '**/episode.h5'
data_aug:
  auto_augment: false
  random_horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1.0
  - 1.0
  random_resize_scale:
  - 0.6
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.485
    - 0.456
    - 0.406
  - - 0.229
    - 0.224
    - 0.225
logging:
  write_tag: jepa
  wandb:
    use_wandb: false
    debug: false
    project: vjepa_wm
    disable_wandb_media: true
    log_media_locally: true
loss:
  cos_loss_weight: 1.0
  l1_loss_weight: 0.0
  l2_loss_weight: 0.0
  smooth_l1_loss_weight: 0.0
meta:
  plan_only_eval_mode: false
  light_eval_only_mode: false
  unroll_decode_eval_only_mode: false
  quick_debug: false
  freeze_encoder: true
  load_checkpoint: false
  load_opt_scale_epoch: true
  read_checkpoint: null
  seed: 234
  eval_freq: 100000
  light_eval_freq: 100000
  save_every_freq: 100000
  dtype: bfloat16
  data_traj_rollout_eval:
    do_data_traj_rollout_eval: false
  energy_landscape_eval:
    do_energy_landscape_eval: false
    energy_landscape_rollout_steps: 1
    energy_landscape_ctxt_window: 3
model:
  grid_size: 16
  tubelet_size_enc: 1
  use_activation_checkpointing: false
  action_conditioning: token
  proprio_encoding: none
  num_frames_pred: 12
  visual_encoder:
    enc_type: dino
    enc_version: dinov3_vitl16
    pretrain_enc_path: null
    pretrain_enc_ckpt_key: null
    embed_dim: 1024
    enc_use_rope: null
    enc_name: null
    use_sdpa_enc: null
    num_frames_enc: null
    uniform_power: true
  action_encoder:
    action_tokens: 1
    action_emb_dim: 0
    act_mlp: false
    action_encoder_inpred: true
  proprio_encoder:
    proprio_tokens: 0
    proprio_emb_dim: 0
    prop_mlp: false
    proprio_encoder_inpred: false
  predictor:
    tubelet_size: 1
    pred_num_heads: 16
    pred_depth: 12
    pred_embed_dim: 1024
    pred_use_extrinsics: false
    pred_type: AdaLN
    act_pred_projector: null
    use_SiLU: null
    use_rope: true
  wm_encoding:
    batchify_video: true
    dup_image: false
    normalize_reps: false
  rollout_cfg:
    rollout_steps: 4
    train_rollout_prefixes: random
    rollout_stop_gradient: true
    ctxt_window_train_rollout: 4
    do_parallel_rollout: null
    do_sequential_rollout: true
    prepend_gt: null
    sampling_scheduler:
      type: linear
      start: 0.0
      end: 0.0
  attn:
    local_window_time: 3
    local_window_h: -1
    local_window_w: -1
  heads_cfg:
    architectures: {}
    pretrain_dec_path: null
optimization:
  main_optimizer: transition_model
  train_heads: false
  transition_model:
    iterations_per_epoch: 2
    ipe_scale: 1.0
    clip_grad: 1
    use_radamw: false
    betas:
    - 0.9
    - 0.995
    eps: 1.0e-08
    weight_decay: 1.0e-07
    final_weight_decay: 1.0e-06
    num_epochs: 1
    warmup: 0
    start_lr: 0.0005
    ref_lr: 0.0005
    final_lr: 0.0005
    mixed_precision: true
evals:
  separate: false
  decode: false
  eval_episodes: 16
  nodes: 1
  low_pri: true
  obs: rgb
  alpha: 0
  override_cfgs_data: true
  override_datasets: true
  wrapper_kwargs:
    ctxt_window: 2
  dump_eval_configs: false
  eval_cfg_paths: []
unroll_decode_evals:
  wrapper_kwargs:
    ctxt_window: 2
  specific_video: false
  specific_video_path: null
  play_in_reverse: false
  save_decoding_only: true
  repeat_hardcode_act: 1
  obs: rgb
